### ISSUE TITLE
Getting ready for packaging

### ISSUE THREAD

**Issue by pdonorio** [mdantonio/rapydo#20]
- [x] remove `operations*` from backend
- [x] copy `commons` into frontend 
- [x] move commons inside the backend into `restapi.utils`
- [x] move `base` stuff into `restapi.core`
- [x] move vanilla/custom stuff into `restapi.custom`
- [x] rename restapi package as rapydo
- [x] fix any docker compose mounting from the above
- [ ] PyPi package would be called `rapydo`

**Comment by mdantonio** [comment]
> copy commons into frontend

It is done

> remove operations* from backend

It is done too

**Comment by mdantonio** [comment]
> move commons inside the backend into restapi.utils

It is done in the "last_refactor" branch

To migrate the vanilla code:

- rename in vanilla all "from commons" into "from restapi.utils"
- rename in vanilla all "import commons" into "import restapi.utils"

**Do not touch the frontend code**, where comons still exists as a copy

**Comment by mdantonio** [comment]
From vanilla remove all relative import. Everything must be converted as absolute import  from restapi

**Comment by pdonorio** [comment]
> from restapi

you mean `rapydo`

**Comment by mdantonio** [comment]
> move base stuff into restapi.core

`restapi/confs/base` became `restapi/core/swagger` (to be homogeneous with restapi/custom/swagger)

`restapi/resources/base` became `restapi/core/resources`

`restapi/utils/models/base` became `restapi/core/models`

`restapi/utils/tasks/base` became `restapi/core/tasks`

`test/base` still remained in the same position

**Comment by mdantonio** [comment]
> move vanilla/custom stuff into restapi.custom

Now the whole vanilla code in mounted into backend as restapi/custom (i'm not fully convinced about this, we should be more selective?)

`vanilla/swagger` was mounted as `restapi/confs/custom` and now is `restapi/custom/swagger`

`vanilla/models` was mounted as `restapi/utils/models/custom` and now is `restapi/custom/models`

`vanilla/tasks` was mounted as `restapi/utils/tasks/custom` and now is `restapi/custom/tasks`

`vanilla/specs` was mounted as `restapi/confs/main` and now is `restapi/custom/specs`

`vanilla/apis` was mounted as `restapi/resources/custom` and now should became `restapi/custom/api`

but we need a homogeneous folder in respect with core. To obtain this just for now i created a link in vanilla apis -> resources. Thanks to that we have apis in `restapi/custom/resources`. To be decided how to fix this

**Comment by mdantonio** [comment]
`restapi` is now renamed as `rapydo`.
All absolute imports have to be modified

**Comment by mdantonio** [comment]
> fix any docker compose mounting from the above

Docker compose is fixed:

- removed the list of mounts of single folders into ***custom
- the whole vanilla code is mounted onto rapydo/custom
- tests/backend is still mounted onto backend/test/custom

To be decided / to be done:

- we have to mounted the whole vanilla code or we should be more selective?
- we should renamed vanilla/apis as vanilla/resources or we should rename backend/core/resources into backend/code/apis?
- test directory is still based on base and custom. We have to modify something?
- some relative import still remained in the backend code... to be fixed

**Comment by mdantonio** [comment]
This is the new backend-rapydo structure:
```
test
|-- base
|   `-- custom

rapydo
|-- confs                     <--- could be removed?
|   |-- current_specs    <--- a static swagger json
|   `-- defaults             <--- link to utils/confs/defaults
|-- core
|   |-- models
|   |-- resources
|   `-- swagger
|-- custom
|   |-- apis
|   |-- models
|   |-- resources -> apis
|   |-- specs
|   |-- swagger
|   |-- tasks
|   `-- tests
|-- resources             <--- should be moved into rapydo.core ?
|   |-- rest
|   `-- services
`-- utils
    |-- attrs
    |-- confs
    |-- formats
    |-- globals
    |-- neo4j
    |-- services
    |-- tasks
    `-- tests

confs                        <--- ?
containers                <--- ?

```

**Comment by mdantonio** [comment]
Moved `rapydo.resources` into `rapydo.core`

**Comment by mdantonio** [comment]
I'm moving many thinks from `rapydo.utils` to `rapydo.core`

**Comment by mdantonio** [comment]
At now the structure is:

```
test
|-- base
|   `-- custom

rapydo
|-- core                <--- many pyfiles are directly here
|   |-- models
|   |-- resources
|   |-- rest
|   |-- services
|   |-- swagger
|   `-- tests
|-- custom
|   |-- apis
|   |-- models
|   |-- resources -> apis
|   |-- specs
|   |-- swagger
|   `-- tasks
`-- utils
    |-- attrs
    |-- confs                 <--- Should be scaled up?
    |-- formats
    |-- globals
    `-- services             <--- a huge __init__ here
```

**Comment by mdantonio** [comment]
> some relative import still remained in the backend code... to be fixed

All relative imports should be removed from backend

**Comment by mdantonio** [comment]
core code is no longer in rapydo.core but directly in rapydo

custom code is no longer in rapydo.custom by one level above

custom code mounting is provided from the project docker compose and no longer by the backend/docker-compose

the use is free to mount with the desired name  (default is 'custom') and then can pass this name via environ


debug.yaml:
```
backend:
    volumes:
        - ..:/code/mycode
    environment:
        VANILLA_PACKAGE: mycode
```

**Comment by pdonorio** [comment]
> but we need a homogeneous folder in respect with core

Not anymore

> To obtain this just for now i created a link in vanilla apis -> resources. Thanks to that we have apis in restapi/custom/resources. To be decided how to fix this

No links. Import should be using the `VANILLA_PACKAGE` env, right?

**Comment by mdantonio** [comment]
At now the structure is:

```

rapydo (server, customization, swagger reader, farm, decorators, expections, basher, attributes)
|-- confs (defaults.yaml, global configuration in __init__)
|-- models (models for swagger, neo4j, sql, mongo, etc)
|-- protocols (bearer, cors, oauth, restful)
|-- resources (base endpoints implementation)
|-- rest (our rest implementation: definition, schema, response)
|-- services
|   |-- authentication
|   |-- celery
|   |-- elasticsearch
|   |-- irods
|   |-- mongo
|   |-- neo4j
|   `-- sql
|-- swagger (swagger definition for base endpoints)
|-- tests (test utility class)
`-- utils (generic utilities)
    `-- formats (yaml reader)

yourvanillacode
|-- apis (custom endpoints implementation)
|-- models (custom models)
|-- specs (project configuration file: project.yaml, blueprint.init)
|-- swagger (swagger definition for custom endpoints)
`-- tasks (implementation of custom celery tasks)

test
|-- base
|   `-- custom

```

**Comment by mdantonio** [comment]
>> To obtain this just for now i created a link in vanilla apis -> resources. Thanks to that we have apis in restapi/custom/resources. To be decided how to fix this

> No links. Import should be using the VANILLA_PACKAGE env, right?

Yes, import is in VANILLA_PACKAGE but the swagger reader now performe an operation like this:

```
for base_dir in [BACKEND_PACKAGE, VANILLA_PACKAGE]
       load("base_dir/resources")
```
An homogeneous directory name (resorces or apis) should be desidered.

However, we can anticipate the IF statement used to determine if an endpoint is base or custom. Based on this check we can also modify the expected path:

```
BACKEND_PACKAGE/resources
VANILLA_PACKAGE/apis
```

**Comment by mdantonio** [comment]
If you did not find any flaws during the porting of EUDAT code, this issue can be closed

**Comment by mdantonio** [comment]
@pdonorio confirmed that the issue can be closed

**Comment by pdonorio** [comment]
> PyPi package would be called `rapydo`

This goes into #23
