### ISSUE TITLE
Remove or enhance the blueprint concept

### ISSUE THREAD

**Issue by mdantonio** [mdantonio/rapydo#30]
Now rapydo supports blueprints and the structure allows to create some independent resource:

- configuration
- docker compose files
- templates
- javascripts

But some other resources are instead shared between all blueprints:

- apis
- css
- libs
- models
- swagger
- tasks
- tests

So now blueprint are not really implemented and supported and we have two options:

1. remove the blueprint concept
2. really allow the blueprint configuration by differentiating all resources

**Comment by mdantonio** [comment]
We decided to remove blueprints.

> configuration

in the specs folder we have:

- blueprint.init -> no longer required (also remove the creation from the do script)
- myproject.yaml -> to be renamed with a fixed name (project_configuration.yaml?)

Please note that after the modification, the specs folder will only contain a single file

> docker compose files

I find a little problem here.
in /containers we jave a "myproject" folder containing debug.yaml, development.yaml, production.yaml files

The myproject folder has to be removed, but we cannot move yaml files directly into the containers folder because it already contains debug/development/production base files. Probably we no longer require base yaml and project yaml so we could merge them

> templates

No problems at all here. Just remove templates/myproject and move templates/myproject/* into templates/*

> javascripts

As above

**Comment by mdantonio** [comment]
`specs/blueprint.init` removed (changed do script and [backend|fronten]/customization.py

`specs/$myproject.yaml` -> renamed into `specs/project_configuration.yaml`

`docker compose files` still untouched (we to decide what to do with them... after that we can remove $1 from do script

`templates/$myproject.yaml/*` moved into `templates/*`

`js/$myproject.yaml/*` moved into `js/*`

**Comment by mdantonio** [comment]
I think that on EUDAT, you should only have to:
- delete vanilla/specs/blueprint.init
- rename vanilla/specs/eudat.yaml ->  vanilla/specs/project_configuration.yaml

- pull backend modification (*not yet pushed*)

**Comment by pdonorio** [comment]
Go ahead and push it then

(^_-)

>

**Comment by mdantonio** [comment]
Pushed. Good luck

**Comment by mdantonio** [comment]
I merged `containers/$mode.yaml` and `containers/$blueprint/$mode.yaml` files

the basic debug.yaml contained some port mapping 
the basic production.yaml contained some pieces of configuration for the proxy

**Comment by mdantonio** [comment]
I already applied such modifications to both rapydo and telethon.

I wait for EUDAT, than we can close the issue (in a near future i will also apply to IMC... but it is not required to keep this issue open waiting for IMC)

**Comment by pdonorio** [comment]
Eudat is fine
