### ISSUE TITLE
Update compose to V3

### ISSUE THREAD

**Issue by pdonorio** [mdantonio/rapydo#7]
I tested some commands and updating the YAML syntax from v1 to v2 is not very difficult at all.

Here it is a comparison:

https://medium.com/@giorgioto/docker-compose-yml-from-v1-to-v2-3c0f8bb7a48e#.qc1f1bm69

Here I have an example from my tests:

https://github.com/pdonorio/pocs/blob/master/rethinkdb_jupyter/docker-compose.yml

**Comment by pdonorio** [comment]
Ok we are up to V3 already. And it's doable, even if not so easy.

- [ ] Actual compose goes under `services`
- [ ] Declare `volumes` at the end of the script
- [ ] Declare `networks` at the end of the script. You can use them to make containers see each other and give them alias. You may define the subnet of a network and the ip of a container. `links`, on which we based our `detect.py` doesn't work anymore. In this case we will activate services if user based env variables are present.
- [ ] Use dependencies to decide in which order containers will start

Note: this file would be compliant with the swarm mode, to deploy a stack.

**Comment by pdonorio** [comment]
Notes on docker compose with the upcoming swarm integration (#2) into rapydo:

- We just build the stack with `docker deploy`. It means that the compose has to be compliant with replications numbers. 0 for what has not to run, 1 for what should run, more for what may scale.
- Compose become just an excuse to use YAML files to have a base configuration and make customizations in debug/development/production
- We could use Jinja templating for the debug/dev/prod files, see [meta-compose](https://github.com/webcrofting/meta-compose) in case
- We need to use the docker compose python library to read and validate the files, and avoid to start if swarm is not enabled.

**Comment by pdonorio** [comment]
Side note: I looked into rancher-compose for extending the docker-compose in python, but rancher writes code in GO. Also [they might not be aligned with V2](https://github.com/rancher/rancher/issues/5715)...

**Comment by pdonorio** [comment]
Docker-compose is going to be needed into the host machine of the developer.

We are going to refer to `virtualenv` python package for this, to avoid the `docker-in-docker` hell.

**Comment by pdonorio** [comment]
getting towards a more stable new version of the docker-compose [here](https://github.com/EUDAT-B2STAGE/http-api/blob/letsencrypt/docker-compose.yml)

**Comment by pdonorio** [comment]
To do:

- [ ] check back DEBUG
- [ ] check back DEVELOPMENT
- [ ] check back PRODUCTION

**Comment by pdonorio** [comment]
A gist from someone else about using docker-compose within python code:
https://github.com/fruch/doorman/blob/master/tests/integration/conftest.py

**Comment by pdonorio** [comment]
Move `networks` and `depends_on` sections inside debug/devel/prod

**Comment by pdonorio** [comment]
So believe it or not, we are done here :)

**Comment by mdantonio** [comment]
> So believe it or not, we are done here :)

In fact I do not believe it.

We don't migrated neither backend nor frontend compose files... You only migrated EUDAT 😄 

I think that we will be able to close this issue on Wednesday (when you will back here)

**Comment by pdonorio** [comment]
In fact sickness made me dump. Of course it only works for eudat vanilla, so now we will make it work inside backend and frontend too, right? 🤣

**Comment by mdantonio** [comment]
Rapydo is now based on compose version 3
